services:
  envoy:
    image: envoyproxy/envoy-dev:36e1878e73d68166a073c0e8324faa86bb6208e3
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - client
      - server
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    # stdin_open: true
    # tty: true
  server:
    build: ./server
    volumes:
      - ./server:/go/src/server
    deploy:
      replicas: 1
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
  nats:
   image: nats:latest
   command: -js -m 8222
   ports:
     - 4222:4222
     - 8222:8222
  test_nats:
   build: ./test_nats
   ports:
     - 8091:8091
   environment:
    - NATS_URL=nats://nats:4222
   depends_on:
    - nats