services:
  envoy:
    image: envoyproxy/envoy-dev:36e1878e73d68166a073c0e8324faa86bb6208e3
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      - JWT_SECRET=${JWT_SECRET}
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    # stdin_open: true
    # tty: true
  server:
    build: ./server
    volumes:
      - ./server:/go/src/server
    deploy:
      replicas: 1